version: '3.8'

services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: recipe-share-sql-server-db
    restart: always
    volumes:
      - ./Databases/sql-server:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "10000:1433"
    networks:
      - recipe-share-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe-share-app
    restart: unless-stopped
    depends_on:
      - sql-server-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server-db,1433;Database=RecipeShareDb;User Id=sa;Password=S3cur3P@ssW0rd!;TrustServerCertificate=True;
    ports:
      - "7069:7069"
    networks:
      - recipe-share-network

networks:
  recipe-share-network:
    driver: bridge
